# Generated by Django 5.0.4 on 2024-06-19 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nursery_app', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
